export const GET_ALL_COURSES_BY_USER_AUTH = "GET_ALL_COURSES_BY_USER_AUTH";
export const GET_ALL_COURSES_BY_USER_AUTH_SUCCESSFUL =
  "GET_ALL_COURSES_BY_USER_AUTH_SUCCESSFUL";
export const GET_ALL_COURSES_BY_USER_AUTH_FAILURE =
  "GET_ALL_COURSES_BY_USER_AUTH_FAILURE ";
