export const GET_COURSE_LANDING_PAGE = "GET_COURSE_LANDING_PAGE";
export const GET_COURSE_LANDING_PAGE_LOGGEDIN_USER =
  "GET_COURSE_LANDING_PAGE_LOGGEDIN_USER";
export const GET_COURSE_LANDING_PAGE_SUCCESSFUL =
  "GET_COURSE_LANDING_PAGE_SUCCESSFUL";
export const GET_COURSE_LANDING_PAGE_FAILURE =
  "GET_COURSE_LANDING_PAGE_FAILURE ";

export const ENROLL_IN_COURSE = "ENROLL_IN_COURSE";
export const ENROLL_IN_COURSE_SUCCESSFUL = "ENROLL_IN_COURSE_SUCCESSFUL";
export const ENROLL_IN_COURSE_FAILURE = "ENROLL_IN_COURSE_FAILURE ";
