export const GET_COURSE_LANDING_PAGE = "GET_COURSE_LANDING_PAGE";
export const GET_COURSE_LANDING_PAGE_LOGGEDIN_USER =
  "GET_COURSE_LANDING_PAGE_LOGGEDIN_USER";
export const GET_COURSE_LANDING_PAGE_SUCCESSFUL =
  "GET_COURSE_LANDING_PAGE_SUCCESSFUL";
export const GET_COURSE_LANDING_PAGE_FAILURE =
  "GET_COURSE_LANDING_PAGE_FAILURE ";
