export const CREATE_COURSE = "CREATE_COURSE";
export const CREATE_COURSE_SUCCESSFUL = "CREATE_COURSE_SUCCESSFUL";
export const CREATE_COURSE_FAILURE = "CREATE_COURSE_FAILURE";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCESSFUL = "UPLOAD_IMAGE_SUCCESSFUL";
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE";
