export const GET_EXPLORE_PAGE_COURSES = "GET_EXPLORE_PAGE_COURSES";
export const GET_EXPLORE_PAGE_COURSES_SUCCESSFUL =
  "GET_EXPLORE_PAGE_COURSES_SUCCESSFUL";
export const GET_EXPLORE_PAGE_COURSES_FAILURE =
  "GET_EXPLORE_PAGE_COURSES_FAILURE";

export const GET_EXPLORE_PAGE_COURSES_BY_CATEGORY =
  "GET_EXPLORE_PAGE_COURSES_BY_CATEGORY";
export const GET_EXPLORE_PAGE_COURSES_BY_CATEGORY_SUCCESSFUL =
  "GET_EXPLORE_PAGE_COURSES_BY_CATEGORY_SUCCESSFUL";
export const GET_EXPLORE_PAGE_COURSES_BY_CATEGORY_FAILURE =
  "GET_EXPLORE_PAGE_COURSES_BY_CATEGORY_FAILURE";
