export const GET_COURSE_EDIT = "GET_COURSE_EDIT";
export const GET_COURSE_EDIT_SUCCESSFUL = "GET_COURSE_EDIT_SUCCESSFUL";
export const GET_COURSE_EDIT_FAILURE = "GET_COURSE_EDIT_FAILURE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const UPDATE_COURSE_SUCCESSFUL = "UPDATE_COURSE_SUCCESSFUL";
export const UPDATE_COURSE_FAILURE = "UPDATE_COURSE_FAILURE";
export const RESET_COURSE_UPDATE_SUCCESS = "RESET_COURSE_UPDATE_SUCCESS";
export const CANCEL_EDIT_COURSE = "CANCEL_EDIT_COURSE";
export const GET_COURSE_LECTURE_LIST = "GET_COURSE_LECTURE_LIST";
export const GET_COURSE_LECTURE_LIST_SUCCESSFUL =
  "GET_COURSE_LECTURE_LIST_SUCCESSFUL";
export const GET_COURSE_LECTURE_LIST_FAILURE =
  "GET_COURSE_LECTURE_LIST_FAILURE";
