export const GET_COURSE_EDIT = "GET_COURSE_EDIT";
export const GET_COURSE_EDIT_SUCCESSFUL = "GET_COURSE_EDIT_SUCCESSFUL";
export const GET_COURSE_EDIT_FAILURE = "GET_COURSE_EDIT_FAILURE";
export const EDIT_COURSE = "EDIT_COURSE";
export const EDIT_COURSE_SUCCESSFUL = "EDIT_COURSE_SUCCESSFUL";
export const EDIT_COURSE_FAILURE = "EDIT_COURSE_FAILURE";
export const CANCEL_EDIT_COURSE = "CANCEL_EDIT_COURSE";
