export const GET_COURSE_LECTURE_LIST = "GET_COURSE_LECTURE_LIST";
export const GET_COURSE_LECTURE_LIST_SUCCESSFUL =
  "GET_COURSE_LECTURE_LIST_SUCCESSFUL";
export const GET_COURSE_LECTURE_LIST_FAILURE =
  "GET_COURSE_LECTURE_LIST_FAILURE";
