export const GET_SINGLE_LECTURE = "GET_SINGLE_LECTURE";
export const GET_SINGLE_LECTURE_SUCCESSFUL = "GET_SINGLE_LECTURE_SUCCESSFUL";
export const GET_SINGLE_LECTURE_FAILURE = "GET_SINGLE_LECTURE_FAILURE ";
