export const GET_LECTURE_EDIT = "GET_LECTURE_EDIT";
export const GET_LECTURE_EDIT_SUCCESSFUL = "GET_LECTURE_EDIT_SUCCESSFUL";
export const GET_LECTURE_EDIT_FAILURE = "GET_LECTURE_EDIT_FAILURE";
export const UPDATE_LECTURE = "UPDATE_LECTURE";
export const UPDATE_LECTURE_SUCCESSFUL = "UPDATE_LECTURE_SUCCESSFUL";
export const UPDATE_LECTURE_FAILURE = "UPDATE_LECTURE_FAILURE";
export const RESET_UPDATE_SUCCESS = "RESET_UPDATE_SUCCESS";
