export const GET_AUTHOR_EDIT = "GET_AUTHOR_EDIT";
export const GET_AUTHOR_EDIT_SUCCESSFUL = "GET_AUTHOR_EDIT_SUCCESSFUL";
export const GET_AUTHOR_EDIT_FAILURE = "GET_AUTHOR_EDIT_FAILURE";
export const UPDATE_AUTHOR = "UPDATE_AUTHOR";
export const UPDATE_AUTHOR_SUCCESSFUL = "UPDATE_AUTHOR_SUCCESSFUL";
export const UPDATE_AUTHOR_FAILURE = "UPDATE_AUTHOR_FAILURE";
